version: '2'

networks:
  dev_net:
    external: true

services:
  blockchain-monitoring:
    container_name: blockchain-monitoring
    image: blockchainmonitoring/blockchain-monitoring:latest
    volumes:
      - $CERTS_ADMIN:/opt/blockchain-monitoring/certs/admin/:rw
#      this is path where we store our certificates
#      and use for in our network-config.yaml
      - $FABRIC_NET_CONFIG:/etc/conf/net-config.yaml
#      if you want customize configuration grafana or influxdb
#      - ./influxdb.conf:/etc/influxdb/influxdb.conf
#      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
#     SCHEDULED_TASKS_DELAY - defaule is 1000 milliseconds
      SCHEDULED_TASKS_DELAY: 10000
#     TIME_EVENT_LIFETIME - defaule is 1 hour
#     DELETE INFO older 1 hour
      TIME_EVENT_LIFETIME: "00:01:00"
    ports:
      - "3000:3000"
      - "8086:8086"
      - "5006:5005" #debug port
    networks:
      dev_net:
        ipv4_address: 172.25.0.135
